name: üß™ CI (Continuous Integration)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js Application
        run: npm run build
        env:
          # Force static export mode for CI testing
          NEXT_BUILD_MODE: 'static-export' 

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Serve Static Files
        run: n npx serve -s out -l 3000 & # Start static server in background
        working-directory: ./web

      - name: Wait for Server to be Ready
        # wait for 60 seconds for server to start up and respond HTTP 200
        timeout-minutes: 1
        run: |
          for i in `seq 1 60`; do
            curl -f http://127.0.0.0.1:3000/en && echo "‚úÖ Static Server is up and responding!" && exit 0
            echo "Waiting for static server to respond HTTP 200... ($i/60)"
            sleep 1
          done
          echo "‚ùå Static Server did not respond HTTP 200 in time!"
          exit 1
        working-directory: ./web

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          # This should match the baseURL in playwright.config.ts
          BASE_URL: http://localhost:3000


