name: üß™ CI (Continuous Integration)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js Application
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start Next.js Server
        run: nohup npm start & # Use npm start to run HOSTNAME=0.0.0.0 node .next/standalone/server.js
        working-directory: ./web

      - name: Wait for Server to be Ready
        # wait for 120 seconds for server to start up and respond HTTP 200
        timeout-minutes: 2
        run: |
          for i in `seq 1 120`; do
            curl -f http://127.0.0.1:3000/en && echo "‚úÖ Server is up and responding!" && exit 0
            echo "Waiting for server to respond HTTP 200... ($i/120)"
            sleep 1
          done
          echo "‚ùå Server did not respond HTTP 200 in time!"
          exit 1
        working-directory: ./web

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          # This should match the baseURL in playwright.config.ts
          BASE_URL: http://localhost:3000


